### ISSUE TITLE
Force using new dorita980 version?

### ISSUE THREAD

**Issue by akwak2015** [koalazak/rest980#14]
Hi,
I updated my dorita980 to new Version becaus of firmware 2.x update.
I also reinstalled the rest980.
But if I tryto use it for example:
192.168.168.11:3000/api/local/info/sys

It seems to usean old version of dorita980. I get the following message inside the browser:
RequestError: Error: connect ECONNREFUSED 192.168.168.28:443
   at new RequestError (/usr/share/iRobot/rest980/node_modules/request-promise-core/lib/errors.js:14:15)
   at Request.plumbing.callback (/usr/share/iRobot/rest980/node_modules/request-promise-core/lib/plumbing.js:87:29)
   at Request.RP$callback [as _callback] (/usr/share/iRobot/rest980/node_modules/request-promise-core/lib/plumbing.js:46:31)
   at self.callback (/usr/share/iRobot/rest980/node_modules/request/request.js:186:22)
   at emitOne (events.js:96:13)
   at Request.emit (events.js:188:7)
   at Request.onRequestError (/usr/share/iRobot/rest980/node_modules/request/request.js:845:8)
   at emitOne (events.js:96:13)
   at ClientRequest.emit (events.js:188:7)
   at TLSSocket.socketErrorListener (_http_client.js:310:9)
   at emitOne (events.js:96:13)
   at TLSSocket.emit (events.js:188:7)
   at emitErrorNT (net.js:1278:8)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by koalazak** [comment]
rest980 is not updated yet to use the new dorita980 version. Im waiting the cloud API in dorita980.

if you are in a hurry, change the dorita980 version in dependecies of rest980 package.json file.
And remove the cloud initialization in routes/

**Comment by akwak2015** [comment]
Ah,
thank you. That was a missunderstanding. I  thought it should work because it is metioned in README.md of dorita980 for Firmware 2.

Regards and thank you for your great work! 

Regards

Gesendet von meinem iPhone 8

**Comment by koalazak** [comment]
Now its possible to configure wich firmware version you have. and use new dorita980 local api. Default to 1.
