### ISSUE TITLE
Cannot read property. 

### ISSUE THREAD

**Issue by JDogg016** [koalazak/rest980#39]
I got everything installed on Docker and when I attempt to run any command nothing happens and my log states “Can’t read property [command]...”

Any ideas?

**Comment by koalazak** [comment]
try to put ENABLE_LOCAL in 'yes' not 'Yes'

**Comment by JDogg016** [comment]
Nope  Didn't work.

```
GET /api/local/info/sys 500 16.828 ms - 148                                                       
TypeError: Cannot read property 'getSys' of undefined                                             
    at /usr/src/app/routes/api.js:149:20                                                          
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:
5)                                                                                                
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)                        
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)               
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:
5)                                                                                                
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22                               
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)     
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)                        
    at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3)              
    at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)                       
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:
5)                                                                                                
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)                 
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7                                
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)     
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)                        
    at /usr/src/app/node_modules/express/lib/router/index.js:635:15                               
    at next (/usr/src/app/node_modules/express/lib/router/index.js:260:14)                        
    at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3)              
    at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)                       
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:
5)                                                                                                
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)                 
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7  
```

**Comment by koalazak** [comment]
did you run the basic code example in dorita980 readme? it works?

**Comment by JDogg016** [comment]
Nope. The response is internal server error

**Comment by koalazak** [comment]
there is no http server in dorita980 basic exmaple so you can't get an "internal server error" running the example code... ¬¬

**Comment by koalazak** [comment]
try to run the basic dorita980 example for trubleshooting. If the example works then rest980 should work...
dorita980 basic example is more easy to debug
