### ISSUE TITLE
500 Error: Connection Refused

### ISSUE THREAD

**Issue by jackmeyer** [koalazak/rest980#42]
Not sure if this rest980 API is supposed to share compatibility with anything that dorita980 works with, so please clarify that for me to begin with.

I have a iRoomba 690 on firmware 3, has been working just fine with dorita980. I am able to run the rest980 API and load the /map page, but all of the requests to my robot's local IP address fail with 500 error. 

GET /api/local/action/dock 500 1031.496 ms - 1438
RequestError: Error: connect ECONNREFUSED 192.168.1.105:443
    at new RequestError (C:\Users\jackt\node_modules\rest980\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\jackt\node_modules\rest980\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\jackt\node_modules\rest980\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\jackt\node_modules\rest980\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\jackt\node_modules\rest980\node_modules\request\request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by koalazak** [comment]
Hi, 
192.168.1.105 is your robot IP or your server ip?
seems like you setup rest980 to use firmware version 1 which has an http api on port 443 instead of use version 2 that uses 8883 port for mqtt.
can you share your env vars or config file? thanks

**Comment by koalazak** [comment]
please setup `FIRMWARE_VERSION` env var or config property `firmwareVersion` to `2` (even if you have firmaware version 3)
