### ISSUE TITLE
Autobuild ARMv7 Container

### ISSUE THREAD

**Issue by jeremywillans** [koalazak/rest980#48]
Is there a possibility of Auto Building a armv7 container on Docker Hub?

I have successfully built and tested this on a Raspberry Pi , using node:alpine.

It does however complain about missing favicon.ico
```
Creating rest980 ... done
Attaching to rest980
rest980    | 
rest980    | > rest980@2.1.0 start /usr/src/app
rest980    | > node ./bin/www
rest980    | 
rest980    | WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
rest980    | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
rest980    | GET / 200 36.481 ms - 89
rest980    | GET /favicon.ico 404 5.961 ms - 136
rest980    | Error: Endpoint not found.
rest980    |     at /usr/src/app/app.js:62:13
rest980    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
rest980    |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
rest980    |     at /usr/src/app/node_modules/express/lib/router/index.js:284:7
rest980    |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
rest980    |     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
rest980    |     at /usr/src/app/node_modules/express/lib/router/index.js:635:15
rest980    |     at next (/usr/src/app/node_modules/express/lib/router/index.js:260:14)
rest980    |     at jsonParser (/usr/src/app/node_modules/body-parser/lib/types/json.js:110:7)
rest980    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
rest980    |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
rest980    |     at /usr/src/app/node_modules/express/lib/router/index.js:284:7
rest980    |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
rest980    |     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
rest980    |     at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3)
rest980    |     at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)
rest980    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
rest980    |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
rest980    |     at /usr/src/app/node_modules/express/lib/router/index.js:284:7
rest980    |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
rest980    |     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
rest980    |     at authHandler (/usr/src/app/app.js:23:48)
```

**Comment by koalazak** [comment]
check #59
