### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by robinposnecker** [koalazak/rest980#56]
Hi there,

I've got an Roomba960 and setted up rest980 on a RaspberryPi3.
When trying to start the map the following error shows up:

pi@raspberrypi:~/Roomba/rest980 $ npm start

> rest980@2.1.0 start /home/pi/Roomba/rest980
> node ./bin/www

GET /map 304 58.307 ms - -
GET /css/style.css 304 16.117 ms - -
GET /js/map.js 304 3.318 ms - -
GET /api/local/info/mission 500 158.811 ms - 1379
RequestError: Error: connect ECONNREFUSED 192.168.188.21:443
    at new RequestError (/home/pi/Roomba/rest980/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/pi/Roomba/rest980/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/pi/Roomba/rest980/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/pi/Roomba/rest980/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/pi/Roomba/rest980/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:73:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

BLID and password query was successful, not sure where to search else.

Thx for your help!

BR
Robin

**Comment by robinposnecker** [comment]
solved. Switvhed to FW Version 2.... sry
